/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiNewsletterRouteImport } from './routes/api/newsletter'
import { Route as ApiContactRouteImport } from './routes/api/contact'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsletterRoute = ApiNewsletterRouteImport.update({
  id: '/api/newsletter',
  path: '/api/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/contact': typeof ApiContactRoute
  '/api/newsletter': typeof ApiNewsletterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/contact': typeof ApiContactRoute
  '/api/newsletter': typeof ApiNewsletterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/contact': typeof ApiContactRoute
  '/api/newsletter': typeof ApiNewsletterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/contact' | '/api/newsletter'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/contact' | '/api/newsletter'
  id: '__root__' | '/' | '/api/contact' | '/api/newsletter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiNewsletterRoute: typeof ApiNewsletterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/newsletter': {
      id: '/api/newsletter'
      path: '/api/newsletter'
      fullPath: '/api/newsletter'
      preLoaderRoute: typeof ApiNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiContactRoute: ApiContactRoute,
  ApiNewsletterRoute: ApiNewsletterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
